spring:
  application:
    name: kitnets-api
  datasource:
    url: jdbc:mariadb://localhost:3306/kitnets_db
    username: kitnet_user
    password: 6551
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never # <--- nÃ£o preciso mais de massa de dados nesse momento
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 20MB