spring:
  application:
    name: kitnets-api
  datasource:
    url: jdbc:mariadb://localhost:3306/kitnets_db
    username: kitnet_user
    password: 6551
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update