spring:
  application:
    name: kitnets-api
  config:
    import: "optional:file:./application-local.yaml"
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
  datasource:
    url: jdbc:mariadb://localhost:3306/kitnets_db
    username: kitnet_user
    password: 6551
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never # <--- nÃ£o preciso mais de massa de dados nesse momento
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 20MB
api:
  security:
    token:
      secret: MinhaSenhaSuperSecreta123